---
- name: Deploy Backend
  hosts: backend
  become: yes

  tasks:
    - name: Install curl for adding Node.js repository
      apt:
        name: curl
        state: present

    - name: Install Node.js and npm using apt
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Install build-essential for compiling npm modules
      apt:
        name: build-essential
        state: present

    - name: Clean up the existing backend directory
      file:
        path: /home/ubuntu/TravelMemory/backend
        state: absent
        force: yes

    - name: Clone the code from Git
      git:
        repo: 'https://github.com/UnpredictablePrashant/TravelMemory.git'
        dest: /home/ubuntu/TravelMemory
        version: "main"
        force: yes  # Force clone if there are existing changes

    - name: Install npm dependencies for backend
      command: npm install
      args:
        chdir: /home/ubuntu/TravelMemory/backend

    - name: Create .env file with MongoDB URL and port
      copy:
        dest: /home/ubuntu/TravelMemory/backend/.env
        content: |
          MONGO_URL=mongodb+srv://mohan:M@han@123@travelmemory.f3do4.mongodb.net/mydatabase
          PORT=3000

    - name: Install Nginx to use as a Reverse Proxy
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Unlink default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create custom Nginx configuration
      copy:
        dest: /etc/nginx/sites-available/custom_server.conf
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://35.183.5.155:3000;  # Backend server IP and port
              }
          }

    - name: Enable the custom Nginx configuration
      file:
        src: /etc/nginx/sites-available/custom_server.conf
        dest: /etc/nginx/sites-enabled/custom_server.conf
        state: link

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted

    - name: Start the backend server
      shell: nohup node /home/ubuntu/TravelMemory/backend/index.js &  # Run backend in the background
